#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# install_nginx_frontend.sh — nginx TLS sidecar for the Odoo MCP server
#
# Summary:
#   Sourced by install_odoo_mcp.sh when MCP_FRONTEND_MODE=nginx.
#   Stands up a SIDECAR nginx container inside deploy/docker-compose.yml
#   (profile `nginx`) that terminates TLS on a configurable host port
#   (default 8443) and proxies to the odoo-mcp service over the docker
#   network. Does NOT touch any pre-existing host-level nginx.
#
# Version: 0.2.0 (Cycle 2.2 — sidecar mode)
# Execution context: sourced by install_odoo_mcp.sh
# ─────────────────────────────────────────────────────────────────────

set -euo pipefail


# ── Inputs (with safe defaults) ───────────────────────────────────────
# Host directory containing nginx.crt + nginx.key. Bind-mounted into
# the sidecar at /etc/nginx/certs:ro. Defaults to the existing cert dir
# already used by your other odoo.giggso.com nginx.
MCP_NGINX_CERT_DIR="${MCP_NGINX_CERT_DIR:-/home/opc/gg-odoo-app/domaincert}"
MCP_NGINX_CERT_FILE="${MCP_NGINX_CERT_FILE:-nginx.crt}"
MCP_NGINX_KEY_FILE="${MCP_NGINX_KEY_FILE:-nginx.key}"

# Public host port. Existing nginx already owns :443, so default to
# 8443. Public URL must then be https://<host>:8443/mcp.
MCP_NGINX_HOST_PORT="${MCP_NGINX_HOST_PORT:-8443}"

# Path prefix the sidecar serves — paired with MCP_PUBLIC_URL ending /mcp.
MCP_NGINX_PATH_PREFIX="${MCP_NGINX_PATH_PREFIX:-/mcp}"


# ── Derived ───────────────────────────────────────────────────────────
# Pull "odoo.giggso.com" out of "https://odoo.giggso.com:8443/mcp".
nginx_server_name() {
  local host="${MCP_PUBLIC_URL#https://}"
  host="${host#http://}"
  host="${host%%/*}"
  host="${host%%:*}"
  echo "$host"
}


# ── Loopback .env (uvicorn plain HTTP, sidecar terminates TLS) ───────
# Overrides install_odoo_mcp.sh's write_env(). HOST is 127.0.0.1 so the
# only ways to reach uvicorn are localhost and the docker network where
# the nginx sidecar lives — not the public internet.
write_env_nginx_mode() {
  mkdir -p "$REPO_DIR/deploy/audit"
  umask 077
cat > "$REPO_DIR/deploy/.env" <<EOF
# ─────────────────────────────────────────────────────────────────────
# Generated by install_odoo_mcp.sh in MCP_FRONTEND_MODE=nginx (sidecar)
# ─────────────────────────────────────────────────────────────────────

# ── Odoo connection ──────────────────────────────────────────────────
ODOO_URL=$ODOO_URL
ODOO_DB_NAME=$ODOO_DB_NAME

# ── Shared signing secret (Odoo addon must match this exact value) ──
ODOO_MCP_CONNECTOR_SECRET=$CONNECTOR_SECRET

# ── Identity verifier (OIDC, optional) ───────────────────────────────
ODOO_MCP_IDENTITY_ISSUER=$IDENTITY_ISSUER
ODOO_MCP_IDENTITY_AUDIENCE=$IDENTITY_AUDIENCE
ODOO_MCP_IDENTITY_JWKS_URL=$IDENTITY_JWKS_URL

# ── Transport + loopback binding (nginx sidecar fronts public TLS) ──
ODOO_MCP_TRANSPORT=sse
ODOO_MCP_HOST=0.0.0.0
ODOO_MCP_PORT=8443
ODOO_MCP_BIND=127.0.0.1
ODOO_MCP_RUN_UID=$MCP_RUN_UID
ODOO_MCP_RUN_GID=$MCP_RUN_GID

# ── TLS handled by sidecar — uvicorn serves plain HTTP only ─────────
ODOO_MCP_TLS_CERT_FILE=
ODOO_MCP_TLS_KEY_FILE=

# ── Public-facing URL (must match sidecar listen + path prefix) ─────
ODOO_MCP_PUBLIC_URL=$MCP_PUBLIC_URL

# ── Sidecar nginx (read by docker-compose.yml) ──────────────────────
MCP_NGINX_HOST_PORT=$MCP_NGINX_HOST_PORT
MCP_NGINX_CERT_DIR=$MCP_NGINX_CERT_DIR

# ── Audit log ────────────────────────────────────────────────────────
ODOO_MCP_AUDIT_LOG=/var/log/odoo-mcp/audit.jsonl
EOF
}


# ── Write the nginx server block into deploy/nginx/conf.d/ ───────────
# Sidecar loads everything in /etc/nginx/conf.d (bind-mounted from
# deploy/nginx/conf.d). No host nginx config is touched.
write_nginx_conf() {
  local server_name conf_dir conf_path
  server_name="$(nginx_server_name)"
  conf_dir="$REPO_DIR/deploy/nginx/conf.d"
  conf_path="$conf_dir/odoo-mcp.conf"

  # Verify the cert + key exist on the host before bind-mounting.
  if [ ! -f "$MCP_NGINX_CERT_DIR/$MCP_NGINX_CERT_FILE" ] \
     || [ ! -f "$MCP_NGINX_CERT_DIR/$MCP_NGINX_KEY_FILE" ]; then
    echo "ERROR: nginx cert/key not found in $MCP_NGINX_CERT_DIR" >&2
    echo "  expected: $MCP_NGINX_CERT_FILE and $MCP_NGINX_KEY_FILE" >&2
    echo "Set MCP_NGINX_CERT_DIR / MCP_NGINX_CERT_FILE / MCP_NGINX_KEY_FILE." >&2
    exit 1
  fi

  mkdir -p "$conf_dir"
  cat > "$conf_path" <<EOF
# ─────────────────────────────────────────────────────────────────────
# Generated by install_nginx_frontend.sh (Cycle 2.2 — sidecar mode)
# Sidecar listens on :443 inside the container, published as host
# port ${MCP_NGINX_HOST_PORT}. Proxies ${MCP_NGINX_PATH_PREFIX}/ to
# the odoo-mcp service over the deploy docker network.
# ─────────────────────────────────────────────────────────────────────

server {
    listen 443 ssl http2;
    server_name $server_name;

    ssl_certificate     /etc/nginx/certs/$MCP_NGINX_CERT_FILE;
    ssl_certificate_key /etc/nginx/certs/$MCP_NGINX_KEY_FILE;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    # MCP server (FastMCP + bearer routes). SSE needs long timeouts.
    location ${MCP_NGINX_PATH_PREFIX}/ {
        proxy_pass         http://odoo-mcp:8443/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_set_header   Connection "";
    }
}
EOF
}


# ── Bring up (or refresh) the sidecar via docker compose ─────────────
restart_sidecar() {
  (cd "$REPO_DIR/deploy" && \
     sudo docker compose --profile nginx up -d nginx)
}


# ── Entry point invoked by install_odoo_mcp.sh ───────────────────────
apply_nginx_frontend() {
  echo ">> Applying nginx sidecar frontend (host port ${MCP_NGINX_HOST_PORT})"
  write_env_nginx_mode
  write_nginx_conf
  restart_sidecar
  echo ">> nginx sidecar ready at $MCP_PUBLIC_URL"
}
