#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# install_nginx_frontend.sh — nginx TLS frontend for the Odoo MCP server
#
# Summary:
#   Sourced by install_odoo_mcp.sh when MCP_FRONTEND_MODE=nginx.
#   Writes the loopback-binding .env, drops an nginx conf.d snippet that
#   reuses the existing odoo.giggso.com certificate, and skips the
#   direct-exposure cert generation path entirely.
#
# Version: 0.1.0 (Cycle 2.1)
# Execution context: sourced by install_odoo_mcp.sh
# ─────────────────────────────────────────────────────────────────────

set -euo pipefail


# ── Inputs (with safe defaults) ───────────────────────────────────────
# Cert files already on the EC2 host from your existing odoo.giggso.com
# nginx setup. Reuse them — no certbot, no Cloudflare, no Caddy.
MCP_NGINX_CERT="${MCP_NGINX_CERT:-/home/opc/gg-odoo-app/domaincert/nginx.crt}"
MCP_NGINX_KEY="${MCP_NGINX_KEY:-/home/opc/gg-odoo-app/domaincert/nginx.key}"

# Path prefix served by nginx — paired with MCP_PUBLIC_URL ending in /mcp.
MCP_NGINX_PATH_PREFIX="${MCP_NGINX_PATH_PREFIX:-/mcp}"

# nginx conf path. /etc/nginx/conf.d is the default include dir on most
# distros. Override if your nginx layout differs.
MCP_NGINX_CONF="${MCP_NGINX_CONF:-/etc/nginx/conf.d/odoo-mcp.conf}"

# Derived: pull "odoo.giggso.com" out of "https://odoo.giggso.com/mcp".
nginx_server_name() {
  local host="${MCP_PUBLIC_URL#https://}"
  host="${host#http://}"
  host="${host%%/*}"
  echo "$host"
}


# ── Write the loopback-binding .env ───────────────────────────────────
# Overrides install_odoo_mcp.sh's default write_env() so HOST is
# 127.0.0.1 and the TLS cert/key fields are blank (nginx terminates TLS).
write_env_nginx_mode() {
  mkdir -p "$REPO_DIR/deploy/audit"
  umask 077
cat > "$REPO_DIR/deploy/.env" <<EOF
# ─────────────────────────────────────────────────────────────────────
# Generated by install_odoo_mcp.sh in MCP_FRONTEND_MODE=nginx
# ─────────────────────────────────────────────────────────────────────

# ── Odoo connection ──────────────────────────────────────────────────
ODOO_URL=$ODOO_URL
ODOO_DB_NAME=$ODOO_DB_NAME

# ── Shared signing secret (Odoo addon must match this exact value) ──
ODOO_MCP_CONNECTOR_SECRET=$CONNECTOR_SECRET

# ── Identity verifier (OIDC) ─────────────────────────────────────────
ODOO_MCP_IDENTITY_ISSUER=$IDENTITY_ISSUER
ODOO_MCP_IDENTITY_AUDIENCE=$IDENTITY_AUDIENCE
ODOO_MCP_IDENTITY_JWKS_URL=$IDENTITY_JWKS_URL

# ── Transport + loopback binding (nginx fronts public TLS) ──────────
ODOO_MCP_TRANSPORT=sse
ODOO_MCP_HOST=127.0.0.1
ODOO_MCP_PORT=8443
ODOO_MCP_BIND=127.0.0.1
ODOO_MCP_RUN_UID=$MCP_RUN_UID
ODOO_MCP_RUN_GID=$MCP_RUN_GID

# ── TLS handled by nginx — uvicorn serves plain HTTP on loopback ────
ODOO_MCP_TLS_CERT_FILE=
ODOO_MCP_TLS_KEY_FILE=

# ── Public-facing URL (must match nginx server_name + path prefix) ──
ODOO_MCP_PUBLIC_URL=$MCP_PUBLIC_URL

# ── Audit log ────────────────────────────────────────────────────────
ODOO_MCP_AUDIT_LOG=/var/log/odoo-mcp/audit.jsonl
EOF
}


# ── Drop the nginx server block ───────────────────────────────────────
# Idempotent: backs up existing conf before overwriting.
write_nginx_conf() {
  local server_name
  server_name="$(nginx_server_name)"

  # Sanity-check the cert files exist before touching nginx.
  if [ ! -f "$MCP_NGINX_CERT" ] || [ ! -f "$MCP_NGINX_KEY" ]; then
    echo "ERROR: nginx cert/key not found:" >&2
    echo "  cert: $MCP_NGINX_CERT" >&2
    echo "  key:  $MCP_NGINX_KEY"  >&2
    echo "Set MCP_NGINX_CERT and MCP_NGINX_KEY to your existing cert paths." >&2
    exit 1
  fi

  # Backup any existing conf so we never silently clobber.
  if [ -f "$MCP_NGINX_CONF" ]; then
    sudo cp "$MCP_NGINX_CONF" "${MCP_NGINX_CONF}.bak.$(date +%Y%m%d%H%M%S)"
  fi

  sudo tee "$MCP_NGINX_CONF" >/dev/null <<EOF
# ─────────────────────────────────────────────────────────────────────
# Generated by install_nginx_frontend.sh (Cycle 2.1)
# Reuses the existing odoo.giggso.com certificate.
# ─────────────────────────────────────────────────────────────────────

server {
    listen 443 ssl http2;
    server_name $server_name;

    ssl_certificate     $MCP_NGINX_CERT;
    ssl_certificate_key $MCP_NGINX_KEY;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    # MCP server (FastMCP + bearer routes). SSE needs long timeouts.
    location ${MCP_NGINX_PATH_PREFIX}/ {
        proxy_pass         http://127.0.0.1:8443/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_set_header   Connection "";
    }

    # NOTE: Odoo location blocks (if any) must be added separately —
    # this file only owns the ${MCP_NGINX_PATH_PREFIX}/ prefix.
}
EOF

  # Validate nginx config and reload only if valid.
  sudo nginx -t
  sudo systemctl reload nginx
}


# ── Entry point invoked by install_odoo_mcp.sh ────────────────────────
apply_nginx_frontend() {
  echo ">> Applying nginx frontend mode"
  write_env_nginx_mode
  write_nginx_conf
  echo ">> nginx frontend ready at $MCP_PUBLIC_URL"
}
