#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# install_nginx_frontend.sh — nginx TLS sidecar for the Odoo MCP server
#
# Summary:
#   Sourced by install_odoo_mcp.sh when MCP_FRONTEND_MODE=nginx. Writes
#   deploy/.env (loopback mode), generates deploy/nginx/conf.d/odoo-mcp.conf,
#   and brings up the nginx sidecar via docker compose --profile nginx.
#   Does NOT touch any pre-existing host-level nginx.
#
# Fixes applied tonight (EC2 hot-patches now in code):
#   Bug 1 — write_env_nginx_mode uses cat> (replace) and sets TLS vars empty,
#            clearing stale Cycle 1 cert paths from .env.
#   Bug 2 — listen directive split to `listen 443 ssl; http2 on;` to silence
#            nginx >= 1.25.1 deprecation warning.
#   Bug 3 — restart_sidecar() exports MCP_NGINX_HOST_PORT + MCP_NGINX_CERT_DIR
#            before docker compose so compose variable substitution in
#            ports:/volumes: resolves from shell env, not just env_file.
#
# Version: 0.4.0 (Cycle 2.3 overnight cleanup)
# Execution context: sourced by install_odoo_mcp.sh
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Inputs ────────────────────────────────────────────────────────────
MCP_NGINX_CERT_DIR="${MCP_NGINX_CERT_DIR:-/home/opc/gg-odoo-app/domaincert}"
MCP_NGINX_CERT_FILE="${MCP_NGINX_CERT_FILE:-nginx.crt}"
MCP_NGINX_KEY_FILE="${MCP_NGINX_KEY_FILE:-nginx.key}"
# 9443: host nginx owns :443, legacy MCP direct mode used :8443 (ADR-002).
MCP_NGINX_HOST_PORT="${MCP_NGINX_HOST_PORT:-9443}"
MCP_NGINX_PATH_PREFIX="${MCP_NGINX_PATH_PREFIX:-/mcp}"

# ── Derived ───────────────────────────────────────────────────────────
nginx_server_name() {
  local h="${MCP_PUBLIC_URL#https://}"
  h="${h#http://}"; h="${h%%/*}"; h="${h%%:*}"; echo "$h"
}

# ── Bug 1: write_env_nginx_mode ───────────────────────────────────────
# cat> replaces the whole file (not append). TLS vars written empty so
# uvicorn stays in plain-HTTP mode. MCP_NGINX_* vars written so
# docker-compose env_file populates them in the container.
write_env_nginx_mode() {
  mkdir -p "$REPO_DIR/deploy/audit"; umask 077
  cat > "$REPO_DIR/deploy/.env" <<EOF
# Generated by install_odoo_mcp.sh — MCP_FRONTEND_MODE=nginx (sidecar)
ODOO_URL=$ODOO_URL
ODOO_DB_NAME=$ODOO_DB_NAME
ODOO_MCP_CONNECTOR_SECRET=$CONNECTOR_SECRET
ODOO_MCP_IDENTITY_ISSUER=$IDENTITY_ISSUER
ODOO_MCP_IDENTITY_AUDIENCE=$IDENTITY_AUDIENCE
ODOO_MCP_IDENTITY_JWKS_URL=$IDENTITY_JWKS_URL
ODOO_MCP_TRANSPORT=sse
ODOO_MCP_HOST=0.0.0.0
ODOO_MCP_PORT=8443
ODOO_MCP_RUN_UID=$MCP_RUN_UID
ODOO_MCP_RUN_GID=$MCP_RUN_GID
# TLS handled by sidecar — uvicorn serves plain HTTP only.
ODOO_MCP_TLS_CERT_FILE=
ODOO_MCP_TLS_KEY_FILE=
ODOO_MCP_PUBLIC_URL=$MCP_PUBLIC_URL
# Read by docker-compose.yml for ports: and volumes: substitution.
MCP_NGINX_HOST_PORT=$MCP_NGINX_HOST_PORT
MCP_NGINX_CERT_DIR=$MCP_NGINX_CERT_DIR
ODOO_MCP_AUDIT_LOG=/var/log/odoo-mcp/audit.jsonl
EOF
}

# ── Bug 2: write_nginx_conf ───────────────────────────────────────────
# Uses `listen 443 ssl; http2 on;` split syntax (nginx >= 1.25.1).
# Trailing slash on proxy_pass strips /mcp prefix from upstream URL;
# the Starlette app mounts routes at /auth/*, /mcp/sse — not under /mcp.
write_nginx_conf() {
  local server_name conf_dir="$REPO_DIR/deploy/nginx/conf.d"
  server_name="$(nginx_server_name)"
  if [ ! -f "$MCP_NGINX_CERT_DIR/$MCP_NGINX_CERT_FILE" ] \
     || [ ! -f "$MCP_NGINX_CERT_DIR/$MCP_NGINX_KEY_FILE" ]; then
    echo "ERROR: cert/key not found in $MCP_NGINX_CERT_DIR" >&2
    echo "Set MCP_NGINX_CERT_DIR / MCP_NGINX_CERT_FILE / MCP_NGINX_KEY_FILE." >&2
    exit 1
  fi
  mkdir -p "$conf_dir"
  cat > "$conf_dir/odoo-mcp.conf" <<EOF
# Generated by install_nginx_frontend.sh (Cycle 2.3 — sidecar mode)
server {
    listen 443 ssl;
    http2 on;
    server_name $server_name;

    ssl_certificate     /etc/nginx/certs/$MCP_NGINX_CERT_FILE;
    ssl_certificate_key /etc/nginx/certs/$MCP_NGINX_KEY_FILE;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    # Trailing slash strips /mcp prefix; upstream sees /auth/whoami etc.
    location ${MCP_NGINX_PATH_PREFIX}/ {
        proxy_pass         http://odoo-mcp:8443/;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_buffering    off;
        proxy_cache        off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        proxy_set_header   Connection "";
    }
}
EOF
}

# ── Bug 3: restart_sidecar ────────────────────────────────────────────
# export before compose so ports:/volumes: substitution in compose.yml
# resolves from shell env (env_file only reaches container, not compose parser).
restart_sidecar() {
  export MCP_NGINX_HOST_PORT MCP_NGINX_CERT_DIR
  (cd "$REPO_DIR/deploy" && sudo docker compose --profile nginx up -d nginx)
}

# ── Entry point ───────────────────────────────────────────────────────
apply_nginx_frontend() {
  echo ">> Applying nginx sidecar frontend (host port ${MCP_NGINX_HOST_PORT})"
  write_env_nginx_mode
  write_nginx_conf
  restart_sidecar
  echo ">> nginx sidecar ready at $MCP_PUBLIC_URL"
}
